let[@axiom] len_geq_0 (l : ilist) (n : int) = ((len l n))#==>((n >= 0))
let[@axiom] len_0 (l : ilist) (res : int) = ((len l res))#==>(((is_nil l))#==>((0 == res)))
let[@axiom] len_0_rev (l : ilist) (res : int) = ((is_nil l))#==>(((0 == res))#==>((len l res)))
let[@axiom] len_0_infer (l : ilist) (res : int) = ((len l res))#==>(((0 == res))#==>((is_nil l)))
let[@axiom] len_0_fwd_pattern (l : ilist) (res : int) = ((is_nil l))#==>(((len l res))#==>((0 == res)))
let[@axiom] len_1 (l : ilist) (xs : ilist) (res : int) = ((len l res))#==>((((is_cons l) && ((tail l) == xs)))#==>(fun ((res_0 [@exists]) : int) -> ((len xs res_0) && ((1 + res_0) == res))))
let[@axiom] len_1_rev (l : ilist) (xs : ilist) (res : int) = (((is_cons l) && ((tail l) == xs)))#==>((fun ((res_0 [@exists]) : int) -> ((len xs res_0) && ((1 + res_0) == res)))#==>((len l res)))
let[@axiom] len_1_fwd_pattern (l : ilist) (xs : ilist) (res : int) = (((is_cons l) && ((tail l) == xs)))#==>(((len l res))#==>(fun ((res_0 [@exists]) : int) -> ((len xs res_0) && ((1 + res_0) == res))))
let[@axiom] all_equal_0 (l : ilist) (x : int) (res : bool) = ((all_equal l x res))#==>(((is_nil l))#==>((true == res)))
let[@axiom] all_equal_0_rev (l : ilist) (x : int) (res : bool) = ((is_nil l))#==>(((true == res))#==>((all_equal l x res)))
let[@axiom] all_equal_0_fwd_pattern (l : ilist) (x : int) (res : bool) = ((is_nil l))#==>(((all_equal l x res))#==>((true == res)))
let[@axiom] all_equal_1 (l : ilist) (x : int) (h : int) (t : ilist) (res : bool) = ((all_equal l x res))#==>((((is_cons l) && ((head l) == h) && ((tail l) == t)))#==>(fun ((res_1 [@exists]) : bool) -> ((all_equal t x res_1) && ((((h == x) && res_1) && res) || ((not (((h == x) && res_1))) && (not (res)))))))
let[@axiom] all_equal_1_rev (l : ilist) (x : int) (h : int) (t : ilist) (res : bool) = (((is_cons l) && ((head l) == h) && ((tail l) == t)))#==>((fun ((res_1 [@exists]) : bool) -> ((all_equal t x res_1) && ((((h == x) && res_1) && res) || ((not (((h == x) && res_1))) && (not (res))))))#==>((all_equal l x res)))
let[@axiom] all_equal_1_fwd_pattern (l : ilist) (x : int) (h : int) (t : ilist) (res : bool) = (((is_cons l) && ((head l) == h) && ((tail l) == t)))#==>(((all_equal l x res))#==>(fun ((res_1 [@exists]) : bool) -> ((all_equal t x res_1) && ((((h == x) && res_1) && res) || ((not (((h == x) && res_1))) && (not (res)))))))