let[@axiom] num_black_0 (t : irbtree) (h : int) (res : bool) = ((num_black t h res))#==>(((is_rbtleaf t))#==>((((h == 0) && res) || ((not ((h == 0))) && (not (res))))))
let[@axiom] num_black_0_rev (t : irbtree) (h : int) (res : bool) = ((is_rbtleaf t))#==>(((((h == 0) && res) || ((not ((h == 0))) && (not (res)))))#==>((num_black t h res)))
let[@axiom] num_black_0_fwd_pattern (t : irbtree) (h : int) (res : bool) = ((is_rbtleaf t))#==>(((num_black t h res))#==>((((h == 0) && res) || ((not ((h == 0))) && (not (res))))))
let[@axiom] num_black_1 (t : irbtree) (h : int) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((num_black t h res))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not c))#==>(fun ((res_0 [@exists]) : bool) -> ((num_black l (h - 1) res_0))#==>(fun ((res_1 [@exists]) : bool) -> ((num_black r (h - 1) res_1) && (((res_0 && res_1) && res) || ((not ((res_0 && res_1))) && (not (res)))))))))
let[@axiom] num_black_1_rev (t : irbtree) (h : int) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = (((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not c))#==>(fun ((res_0 [@exists]) : bool) -> ((num_black l (h - 1) res_0))#==>((fun ((res_1 [@exists]) : bool) -> ((num_black r (h - 1) res_1) && (((res_0 && res_1) && res) || ((not ((res_0 && res_1))) && (not (res))))))#==>((num_black t h res)))))
let[@axiom] num_black_1_fwd_pattern (t : irbtree) (h : int) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((not c))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((num_black t h res))#==>(fun ((res_0 [@exists]) : bool) -> fun ((res_1 [@exists]) : bool) -> ((num_black l (h - 1) res_0) && (num_black r (h - 1) res_1) && (((res_0 && res_1) && res) || ((not ((res_0 && res_1))) && (not (res))))))))
let[@axiom] num_black_2 (t : irbtree) (h : int) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((num_black t h res))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>(fun ((res_2 [@exists]) : bool) -> ((num_black l h res_2))#==>(fun ((res_3 [@exists]) : bool) -> ((num_black r h res_3) && (((res_2 && res_3) && res) || ((not ((res_2 && res_3))) && (not (res)))))))))
let[@axiom] num_black_2_rev (t : irbtree) (h : int) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = (((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>(fun ((res_2 [@exists]) : bool) -> ((num_black l h res_2))#==>((fun ((res_3 [@exists]) : bool) -> ((num_black r h res_3) && (((res_2 && res_3) && res) || ((not ((res_2 && res_3))) && (not (res))))))#==>((num_black t h res)))))
let[@axiom] num_black_2_fwd_pattern (t : irbtree) (h : int) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((not ((not c))))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((num_black t h res))#==>(fun ((res_2 [@exists]) : bool) -> fun ((res_3 [@exists]) : bool) -> ((num_black l h res_2) && (num_black r h res_3) && (((res_2 && res_3) && res) || ((not ((res_2 && res_3))) && (not (res))))))))
let[@axiom] no_red_red_0 (t : irbtree) (res : bool) = ((no_red_red t res))#==>(((is_rbtleaf t))#==>((true == res)))
let[@axiom] no_red_red_0_rev (t : irbtree) (res : bool) = ((is_rbtleaf t))#==>(((true == res))#==>((no_red_red t res)))
let[@axiom] no_red_red_0_fwd_pattern (t : irbtree) (res : bool) = ((is_rbtleaf t))#==>(((no_red_red t res))#==>((true == res)))
let[@axiom] no_red_red_1 (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((no_red_red t res))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not c))#==>(fun ((res_4 [@exists]) : bool) -> ((no_red_red l res_4))#==>(fun ((res_5 [@exists]) : bool) -> ((no_red_red r res_5) && (((res_4 && res_5) && res) || ((not ((res_4 && res_5))) && (not (res)))))))))
let[@axiom] no_red_red_1_rev (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = (((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not c))#==>(fun ((res_4 [@exists]) : bool) -> ((no_red_red l res_4))#==>((fun ((res_5 [@exists]) : bool) -> ((no_red_red r res_5) && (((res_4 && res_5) && res) || ((not ((res_4 && res_5))) && (not (res))))))#==>((no_red_red t res)))))
let[@axiom] no_red_red_1_fwd_pattern (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((not c))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((no_red_red t res))#==>(fun ((res_4 [@exists]) : bool) -> fun ((res_5 [@exists]) : bool) -> ((no_red_red l res_4) && (no_red_red r res_5) && (((res_4 && res_5) && res) || ((not ((res_4 && res_5))) && (not (res))))))))
let[@axiom] no_red_red_2 (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c' : bool) (c'' : bool) (res : bool) = ((no_red_red t res))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>((((is_rbtnode l) && ((color l) == c')))#==>((((is_rbtnode r) && ((color r) == c'')))#==>(fun ((res_6 [@exists]) : bool) -> ((no_red_red l res_6))#==>(fun ((res_7 [@exists]) : bool) -> ((no_red_red r res_7) && ((((not c') && ((not c'') && (res_6 && res_7))) && res) || ((not (((not c') && ((not c'') && (res_6 && res_7))))) && (not (res)))))))))))
let[@axiom] no_red_red_2_rev (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c' : bool) (c'' : bool) (res : bool) = (((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>((((is_rbtnode l) && ((color l) == c')))#==>((((is_rbtnode r) && ((color r) == c'')))#==>(fun ((res_6 [@exists]) : bool) -> ((no_red_red l res_6))#==>((fun ((res_7 [@exists]) : bool) -> ((no_red_red r res_7) && ((((not c') && ((not c'') && (res_6 && res_7))) && res) || ((not (((not c') && ((not c'') && (res_6 && res_7))))) && (not (res))))))#==>((no_red_red t res)))))))
let[@axiom] no_red_red_2_fwd_pattern (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c' : bool) (c'' : bool) (res : bool) = (((is_rbtnode r) && ((color r) == c'')))#==>((((is_rbtnode l) && ((color l) == c')))#==>(((not ((not c))))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((no_red_red t res))#==>(fun ((res_6 [@exists]) : bool) -> fun ((res_7 [@exists]) : bool) -> ((no_red_red l res_6) && (no_red_red r res_7) && ((((not c') && ((not c'') && (res_6 && res_7))) && res) || ((not (((not c') && ((not c'') && (res_6 && res_7))))) && (not (res))))))))))
let[@axiom] no_red_red_3 (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c' : bool) (res : bool) = ((no_red_red t res))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>((((is_rbtnode l) && ((color l) == c')))#==>(((is_rbtleaf r))#==>(fun ((res_8 [@exists]) : bool) -> ((no_red_red l res_8) && ((((not c') && res_8) && res) || ((not (((not c') && res_8))) && (not (res))))))))))
let[@axiom] no_red_red_3_rev (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c' : bool) (res : bool) = (((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>((((is_rbtnode l) && ((color l) == c')))#==>(((is_rbtleaf r))#==>((fun ((res_8 [@exists]) : bool) -> ((no_red_red l res_8) && ((((not c') && res_8) && res) || ((not (((not c') && res_8))) && (not (res))))))#==>((no_red_red t res))))))
let[@axiom] no_red_red_3_fwd_pattern (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c' : bool) (res : bool) = ((is_rbtleaf r))#==>((((is_rbtnode l) && ((color l) == c')))#==>(((not ((not c))))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((no_red_red t res))#==>(fun ((res_8 [@exists]) : bool) -> ((no_red_red l res_8) && ((((not c') && res_8) && res) || ((not (((not c') && res_8))) && (not (res))))))))))
let[@axiom] no_red_red_4 (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c'' : bool) (res : bool) = ((no_red_red t res))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>(((is_rbtleaf l))#==>((((is_rbtnode r) && ((color r) == c'')))#==>(fun ((res_9 [@exists]) : bool) -> ((no_red_red r res_9) && ((((not c'') && res_9) && res) || ((not (((not c'') && res_9))) && (not (res))))))))))
let[@axiom] no_red_red_4_rev (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c'' : bool) (res : bool) = (((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>(((is_rbtleaf l))#==>((((is_rbtnode r) && ((color r) == c'')))#==>((fun ((res_9 [@exists]) : bool) -> ((no_red_red r res_9) && ((((not c'') && res_9) && res) || ((not (((not c'') && res_9))) && (not (res))))))#==>((no_red_red t res))))))
let[@axiom] no_red_red_4_fwd_pattern (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (c'' : bool) (res : bool) = (((is_rbtnode r) && ((color r) == c'')))#==>(((is_rbtleaf l))#==>(((not ((not c))))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((no_red_red t res))#==>(fun ((res_9 [@exists]) : bool) -> ((no_red_red r res_9) && ((((not c'') && res_9) && res) || ((not (((not c'') && res_9))) && (not (res))))))))))
let[@axiom] no_red_red_5 (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((no_red_red t res))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>(((is_rbtleaf l))#==>(((is_rbtleaf r))#==>((true == res))))))
let[@axiom] no_red_red_5_rev (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = (((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((not ((not c))))#==>(((is_rbtleaf l))#==>(((is_rbtleaf r))#==>(((true == res))#==>((no_red_red t res))))))
let[@axiom] no_red_red_5_fwd_pattern (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((is_rbtleaf r))#==>(((is_rbtleaf l))#==>(((not ((not c))))#==>((((is_rbtnode t) && ((color t) == c) && ((left t) == l) && ((right t) == r)))#==>(((no_red_red t res))#==>((true == res))))))

(*****)

let[@axiom] ax_4_proposed (t : irbtree) (h : int) (c : bool) (l : irbtree) (r : irbtree) (res : bool) (res_0 : bool) (res_1 : bool) = (((is_rbtnode t)) && ((((color t)) == (c)) && ((((left t)) == (l)) && (((right t)) == (r)))))#==>(((not (c)))#==>(((num_black l ((h) - (1)) res_0))#==>((((num_black r ((h) - (1)) res_1)) && ((((res_0) && (res_1)) && (res)) || (((not ((res_0) && (res_1)))) && ((not (res))))))#==>((num_black t h res)))))

let[@axiom] ax_noredred_proposed (t : irbtree) (l' : irbtree) (v' : int) (r' : irbtree) = ((no_red_red l' true))#==>(((no_red_red r' true))#==>(((((((is_rbtnode t)) && (((color t)) == (false))) && (((left t)) == (l'))) && (((value t)) == (v'))) && (((right t)) == (r')))#==>((no_red_red t true))))

let[@axiom] ax_no_red_red_proposed (t : irbtree) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((no_red_red t res))#==>((((is_rbtnode t)) && ((((color t)) == (c)) && ((((left t)) == (l)) && (((right t)) == (r)))))#==>(((not (c)))#==>(fun ((res_4 [@exists]) : bool) -> ((no_red_red l res_4)) && (fun ((res_5 [@exists]) : bool) -> ((no_red_red r res_5)) && ((((res_4) && (res_5)) && (res)) || (((not ((res_4) && (res_5)))) && ((not (res)))))))))

let[@axiom] ax_num_black_0_red_proposed (t : irbtree) (c'' : bool) (l'' : irbtree) (v'' : int) (r'' : irbtree) = ((((((is_rbtnode t)) && (((color t)) == (c''))) && (((left t)) == (l''))) && (((value t)) == (v''))) && (((right t)) == (r'')))#==>(((num_black t 0 true))#==>(c''))

let[@axiom] ax_num_black_pos_proposed (t : irbtree) (h : int) = ((num_black t h true))#==>((h) >= (0))

let[@axiom] ax_num_black_proposed (t : irbtree) (h : int) (c : bool) (l : irbtree) (r : irbtree) (res : bool) = ((num_black t h res))#==>((((is_rbtnode t)) && ((((color t)) == (c)) && ((((left t)) == (l)) && (((right t)) == (r)))))#==>(((not (c)))#==>(fun ((res_0 [@exists]) : bool) -> ((num_black l ((h) - (1)) res_0)) && (fun ((res_1 [@exists]) : bool) -> ((num_black r ((h) - (1)) res_1)) && ((((res_0) && (res_1)) && (res)) || (((not ((res_0) && (res_1)))) && ((not (res)))))))))

let[@axiom] ax_no_red_red_color_true_proposed (t : irbtree) (l' : irbtree) (v' : int) (r' : irbtree) = ((((((is_rbtnode t)) && (((color t)) == (true))) && (((left t)) == (l'))) && (((value t)) == (v'))) && (((right t)) == (r')))#==>(((no_red_red l' true))#==>(((no_red_red r' true))#==>((((is_rbtleaf l')) || (((is_rbtnode l')) && ((not (((color l')) == (true))))))#==>((((is_rbtleaf r')) || (((is_rbtnode r')) && ((not (((color r')) == (true))))))#==>((no_red_red t true))))))

let[@axiom] ax_num_black_color_true_proposed (t : irbtree) (h_3 : int) (l' : irbtree) (v' : int) (r' : irbtree) = ((((((is_rbtnode t)) && (((color t)) == (true))) && (((left t)) == (l'))) && (((value t)) == (v'))) && (((right t)) == (r')))#==>(((num_black l' h_3 true))#==>(((num_black r' h_3 true))#==>((num_black t h_3 true))))

let[@axiom] ax_num_black_black_false_node_proposed (t : irbtree) (h : int) (l' : irbtree) (v' : int) (r' : irbtree) = ((((((is_rbtnode t)) && (((color t)) == (false))) && (((left t)) == (l'))) && (((value t)) == (v'))) && (((right t)) == (r')))#==>(((num_black l' ((h) - (1)) true))#==>(((num_black r' ((h) - (1)) true))#==>((num_black t h true))))

let[@axiom] ax_no_red_red_false_node_2_proposed (t : irbtree) (l' : irbtree) (v' : int) (r' : irbtree) = ((((((is_rbtnode t)) && (((color t)) == (true))) && (((left t)) == (l'))) && (((value t)) == (v'))) && (((right t)) == (r')))#==>(((no_red_red l' true))#==>((((is_rbtleaf l')) || (((is_rbtnode l')) && ((not (((color l')) == (true))))))#==>(((no_red_red r' true))#==>((((is_rbtleaf r')) || (((is_rbtnode r')) && ((not (((color r')) == (true))))))#==>((no_red_red t true))))))

let[@axiom] ax_no_red_red_false_node_proposed (t : irbtree) (h : int) (l' : irbtree) (v' : int) (r' : irbtree) = ((((((is_rbtnode t)) && (((color t)) == (false))) && (((left t)) == (l'))) && (((value t)) == (v'))) && (((right t)) == (r')))#==>(((no_red_red l' true))#==>((((((h) - (1))) == (0))#==>(((is_rbtleaf l')) || (((is_rbtnode l')) && ((not (((color l')) == (false)))))))#==>(((no_red_red r' true))#==>((((((h) - (1))) == (0))#==>(((is_rbtleaf r')) || (((is_rbtnode r')) && ((not (((color r')) == (false)))))))#==>((no_red_red t true))))))

let[@axiom] ax_num_black_black_true_node_proposed (t : irbtree) (h : int) (l' : irbtree) (v' : int) (r' : irbtree) = ((((((is_rbtnode t)) && (((color t)) == (true))) && (((left t)) == (l'))) && (((value t)) == (v'))) && (((right t)) == (r')))#==>(((num_black l' h true))#==>(((num_black r' h true))#==>((num_black t h true))))