let[@axiom] len_geq_0 (l : ilist) (n : int) = ((len l n))#==>((n >= 0))
let[@axiom] len_0 (l : ilist) (res : int) = ((len l res))#==>(((is_nil l))#==>((0 == res)))
let[@axiom] len_0_rev (l : ilist) (res : int) = ((is_nil l))#==>(((0 == res))#==>((len l res)))
let[@axiom] len_0_infer (l : ilist) (res : int) = ((len l res))#==>(((0 == res))#==>((is_nil l)))
let[@axiom] len_0_fwd_pattern (l : ilist) (res : int) = ((is_nil l))#==>(((len l res))#==>((0 == res)))
let[@axiom] len_1 (l : ilist) (xs : ilist) (res : int) = ((len l res))#==>((((is_cons l) && ((tail l) == xs)))#==>(fun ((res_0 [@exists]) : int) -> ((len xs res_0) && ((1 + res_0) == res))))
let[@axiom] len_1_rev (l : ilist) (xs : ilist) (res : int) = (((is_cons l) && ((tail l) == xs)))#==>((fun ((res_0 [@exists]) : int) -> ((len xs res_0) && ((1 + res_0) == res)))#==>((len l res)))
let[@axiom] len_1_fwd_pattern (l : ilist) (xs : ilist) (res : int) = (((is_cons l) && ((tail l) == xs)))#==>(((len l res))#==>(fun ((res_0 [@exists]) : int) -> ((len xs res_0) && ((1 + res_0) == res))))
let[@axiom] sorted_0 (l : ilist) (res : bool) = ((sorted l res))#==>(((is_nil l))#==>((true == res)))
let[@axiom] sorted_0_rev (l : ilist) (res : bool) = ((is_nil l))#==>(((true == res))#==>((sorted l res)))
let[@axiom] sorted_0_fwd_pattern (l : ilist) (res : bool) = ((is_nil l))#==>(((sorted l res))#==>((true == res)))
let[@axiom] sorted_1 (l : ilist) (x : int) (xs : ilist) (res : bool) = ((sorted l res))#==>((((is_cons l) && ((head l) == x) && ((tail l) == xs)))#==>(((is_nil xs))#==>((true == res))))
let[@axiom] sorted_1_rev (l : ilist) (x : int) (xs : ilist) (res : bool) = (((is_cons l) && ((head l) == x) && ((tail l) == xs)))#==>(((is_nil xs))#==>(((true == res))#==>((sorted l res))))
let[@axiom] sorted_1_fwd_pattern (l : ilist) (x : int) (xs : ilist) (res : bool) = ((is_nil xs))#==>((((is_cons l) && ((head l) == x) && ((tail l) == xs)))#==>(((sorted l res))#==>((true == res))))
let[@axiom] sorted_2 (l : ilist) (x : int) (xs : ilist) (y : int) (res : bool) = ((sorted l res))#==>((((is_cons l) && ((head l) == x) && ((tail l) == xs)))#==>((((is_cons xs) && ((head xs) == y)))#==>(fun ((res_1 [@exists]) : bool) -> ((sorted xs res_1) && ((((x <= y) && res_1) && res) || ((not (((x <= y) && res_1))) && (not (res))))))))
let[@axiom] sorted_2_rev (l : ilist) (x : int) (xs : ilist) (y : int) (res : bool) = (((is_cons l) && ((head l) == x) && ((tail l) == xs)))#==>((((is_cons xs) && ((head xs) == y)))#==>((fun ((res_1 [@exists]) : bool) -> ((sorted xs res_1) && ((((x <= y) && res_1) && res) || ((not (((x <= y) && res_1))) && (not (res))))))#==>((sorted l res))))
let[@axiom] sorted_2_fwd_pattern (l : ilist) (x : int) (xs : ilist) (y : int) (res : bool) = (((is_cons xs) && ((head xs) == y)))#==>((((is_cons l) && ((head l) == x) && ((tail l) == xs)))#==>(((sorted l res))#==>(fun ((res_1 [@exists]) : bool) -> ((sorted xs res_1) && ((((x <= y) && res_1) && res) || ((not (((x <= y) && res_1))) && (not (res))))))))